spring:
  application:
    name: elegant-rpc-example-client
netty:
  client:
    server-address: 192.168.62.236:8090
    register-name: elegant-rpc-example-client
    route-strategy:
server:
  port: 8801